// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfjjhjnicbkvkfnpyrbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhmampoam5pY2JrdmtmbnB5cmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MzI0NjksImV4cCI6MjA3NjEwODQ2OX0.lakrr_Usbt2BJYooXTKjgr96lMtpwBfawUHhxtfuXlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});